### ISSUE TITLE
autoincrement property ignored on Column

### ISSUE THREAD

**Issue by marcoceppi** [SunDwarf/asyncqlio#47]
When attempting to do an insert on a new record where an auto-incrementing primary key field is omitted, `run_insert_query` fails trying to test Column.autoincrement property.

```
Traceback (most recent call last):
  File "app/meet/meeting.py", line 39, in get_or_create_code
    await sess.add(m)
  File ".venv/lib/python3.6/site-packages/asyncqlio/orm/session.py", line 456, in add
    return await self.insert_now(row)
  File ".venv/lib/python3.6/site-packages/asyncqlio/orm/session.py", line 273, in insert_now
    result = await self.run_insert_query(q)
  File ".venv/lib/python3.6/site-packages/asyncqlio/orm/session.py", line 363, in run_insert_query
    if sum(1 for x in row.table.iter_columns() if x.autoincrement) == 1:
  File ".venv/lib/python3.6/site-packages/asyncqlio/orm/session.py", line 363, in <genexpr>
    if sum(1 for x in row.table.iter_columns() if x.autoincrement) == 1:
  File ".venv/lib/python3.6/site-packages/asyncqlio/orm/schema/column.py", line 188, in __getattr__
    item)) from None
AttributeError: Column object 'id' has no attribute 'autoincrement'
```

**Comment by marcoceppi** [comment]
This seems to be due to `__getattr__`, https://stackoverflow.com/a/25115607/196832

**Comment by marcoceppi** [comment]
Ugh, it's even worse. Based on this http://blog.devork.be/2011/06/using-getattr-and-property_17.html and some monkey patching the dep in my virtualenv, something in `autoincrement` property is raising `AttributeError` which obscures what is raising the error.

**Comment by marcoceppi** [comment]
My `table.metadata.bind` is `None` leading to the attribute error of `'NoneType' object has no attribute 'dialect'`

**Comment by marcoceppi** [comment]
This seems to stem from the fact that I don't invoke `db.bind_tables`. However, after doing so get errors during table binding:

```
Traceback (most recent call last):
  File "server.py", line 119, in <module>
    loop.run_until_complete(init_db(app))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "app/utils/middleware.py", line 19, in init_db
    app['db'].bind_tables(models.Meeting.metadata)
  File ".venv/lib/python3.6/site-packages/asyncqlio/db.py", line 108, in bind_tables
    md.setup_tables()
  File ".venv/lib/python3.6/site-packages/asyncqlio/orm/schema/table.py", line 82, in setup_tables
    self.resolve_floating_relationships()
  File ".venv/lib/python3.6/site-packages/asyncqlio/orm/schema/table.py", line 154, in resolve_floating_relationships
    table, column = foreignkey._f_name.split(".")
  File ".venv/lib/python3.6/site-packages/asyncqlio/orm/schema/column.py", line 188, in __getattr__
    item)) from None
AttributeError: Column object 'id' has no attribute '_f_name'
```

**Comment by marcoceppi** [comment]
There was a typo in a Table definition that wasn't being bound but showed up anyways during rendering. This was a rabbit hole, but binding tables isn't really well documented - which is my take away.

**Comment by SunDwarf** [comment]
Yeah, unfortunately documentation isn't really the strong point (or any point) of the library. I intended to do more at some point but I started working on other projects and it got pushed down my todo-list.

**Comment by marcoceppi** [comment]
That's fine, I've been searching for a good async SQLAlchemy library. The last one I landed on, peewee_async left me wanting more. There's a lot of promise in this library so I intent to keep fighting my way through :grinning:
